from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest

from review_assist.cli import main
from review_assist.figure_style_model import (
    FIGURE_RECIPES_PATH,
    FIGURE_RENDER_JOBS_PATH,
    FIGURE_STYLE_OVERRIDES_PATH,
    FIGURE_VERSIONS_PATH,
    FigureStyleModelError,
    active_style_override,
    approve_figure_version,
    approved_figure_version,
    initialize_figure_style_model,
    make_render_job,
    make_sparse_style_override,
    reset_project_style_override,
    reset_style_override,
    save_project_style_override,
)


def test_initialize_figure_style_model_creates_recipes_and_v1_versions(tmp_path: Path) -> None:
    project_dir = write_project_with_figures(tmp_path)

    result = initialize_figure_style_model(project_dir)

    recipes = read_json(project_dir / FIGURE_RECIPES_PATH)
    versions = read_json(project_dir / FIGURE_VERSIONS_PATH)
    overrides = read_json(project_dir / FIGURE_STYLE_OVERRIDES_PATH)
    render_jobs = read_json(project_dir / FIGURE_RENDER_JOBS_PATH)
    assert result["analysis_artifacts_mutated"] is False
    assert recipes["recipe_count"] == 15
    assert versions["version_count"] == 15
    assert overrides["overrides"] == []
    assert render_jobs["render_jobs"] == []

    recipe = next(item for item in recipes["recipes"] if item["figure_id"] == "figure-wetlands-waterbodies")
    assert recipe["analysis_snapshot_id"] == result["analysis_snapshot"]["analysis_snapshot_id"]
    assert recipe["default_layer_order"] == [
        "comparison_units",
        "source:usfws_nwi_wetlands",
        "basemap:1",
    ]
    source_layer = next(layer for layer in recipe["layers"] if layer["layer_id"] == "source:usfws_nwi_wetlands")
    assert source_layer["default_style"]["stroke_color"] == "#FFE500"
    assert source_layer["default_legend_label"] == "National Wetlands Inventory"
    assert recipe["generated_artifact"]["image_path"] == "maps/figures/figure-wetlands-waterbodies.png"
    assert recipe["presentation_only"] is True

    version = next(item for item in versions["versions"] if item["figure_id"] == "figure-wetlands-waterbodies")
    assert version["version_number"] == 1
    assert version["approval_state"] == "autogenerated"
    assert version["source_image_status"] == "existing_generated_image"


def test_sparse_override_serialization_and_reset() -> None:
    override = make_sparse_style_override(
        project_id="demo",
        figure_id="figure-wetlands-waterbodies",
        analysis_snapshot_id="analysis-snapshot-123",
        created_at="2026-05-22T00:00:00+00:00",
        layers=[
            {
                "layer_id": "source:usfws_nwi_wetlands",
                "visible": False,
                "stroke_color": "#00AAFF",
                "display_name": "",
                "point_size": None,
            },
            {"layer_id": "comparison_units"},
        ],
    )

    assert override["overrides"] == [
        {
            "layer_id": "source:usfws_nwi_wetlands",
            "stroke_color": "#00AAFF",
            "visible": False,
        }
    ]

    artifact = {"override_count": 1, "overrides": [override]}
    reset = reset_style_override(artifact, "figure-wetlands-waterbodies")
    assert reset["override_count"] == 1
    assert reset["overrides"][0]["status"] == "reset"
    assert active_style_override(reset, "figure-wetlands-waterbodies") is None


def test_sparse_override_rejects_unsupported_fields() -> None:
    with pytest.raises(FigureStyleModelError, match="Unsupported style override fields"):
        make_sparse_style_override(
            project_id="demo",
            figure_id="figure-wetlands-waterbodies",
            analysis_snapshot_id="analysis-snapshot-123",
            layers=[{"layer_id": "source:usfws_nwi_wetlands", "buffer_distance": 100}],
        )


def test_render_job_validation() -> None:
    job = make_render_job(
        project_id="demo",
        figure_id="figure-wetlands-waterbodies",
        analysis_snapshot_id="analysis-snapshot-123",
        figure_recipe_id="figure-wetlands-waterbodies:recipe:v1",
        style_override_id="figure-wetlands-waterbodies:override:abc",
        created_at="2026-05-22T00:00:00+00:00",
    )

    assert job["status"] == "queued"
    assert job["output_format"] == "png"

    with pytest.raises(FigureStyleModelError, match="Unsupported render job status"):
        make_render_job(
            project_id="demo",
            figure_id="figure-wetlands-waterbodies",
            analysis_snapshot_id="analysis-snapshot-123",
            figure_recipe_id="figure-wetlands-waterbodies:recipe:v1",
            status="done",
        )


def test_cli_initializer_writes_metadata_without_mutating_analysis_artifacts(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    project_dir = write_project_with_figures(tmp_path)
    figures_path = project_dir / "deliverable" / "figures.json"
    before = figures_path.read_text(encoding="utf-8")

    assert main(["initialize-figure-style-model", str(project_dir), "--json"]) == 0

    payload = json.loads(capsys.readouterr().out)
    assert payload["recipe_count"] == 15
    assert payload["version_count"] == 15
    assert figures_path.read_text(encoding="utf-8") == before
    assert not (project_dir / "review_queue" / "review_queue.json").exists()
    assert not (project_dir / "exports" / "export_manifest.json").exists()


def test_save_project_style_override_is_sparse_and_auditable(tmp_path: Path) -> None:
    project_dir = write_project_with_figures(tmp_path)

    result = save_project_style_override(
        project_dir,
        "figure-wetlands-waterbodies",
        [
            {
                "layer_id": "source:usfws_nwi_wetlands",
                "visible": "true",
                "display_name": "National Wetlands Inventory",
                "stroke_color": "#00aaff",
                "fill_opacity": "0.42",
            }
        ],
    )

    artifact = read_json(project_dir / FIGURE_STYLE_OVERRIDES_PATH)
    override = active_style_override(artifact, "figure-wetlands-waterbodies")

    assert result["override_saved"] is True
    assert result["model_initialized"] is True
    assert override is not None
    assert override["status"] == "active"
    assert override["created_by"] == "local_reviewer"
    assert override["updated_by"] == "local_reviewer"
    assert override["overrides"] == [{"layer_id": "source:usfws_nwi_wetlands", "stroke_color": "#00AAFF"}]


def test_save_project_style_override_accepts_comparison_feature_layers(tmp_path: Path) -> None:
    project_dir = write_project_with_figures(tmp_path)

    save_project_style_override(
        project_dir,
        "figure-wetlands-waterbodies",
        [
            {
                "layer_id": "comparison_units:unit-2",
                "display_name": "Comparison 2",
                "stroke_color": "#00AAFF",
                "fill_opacity": "0.42",
                "stroke_width": "1.25",
                "point_size": "12.50",
            }
        ],
    )

    artifact = read_json(project_dir / FIGURE_STYLE_OVERRIDES_PATH)
    override = active_style_override(artifact, "figure-wetlands-waterbodies")

    assert override is not None
    assert override["overrides"] == [
        {
            "layer_id": "comparison_units:unit-2",
            "display_name": "Comparison 2",
            "fill_opacity": 0.42,
            "point_size": 12.5,
            "stroke_color": "#00AAFF",
            "stroke_width": 1.25,
        }
    ]


def test_saving_defaults_supersedes_active_override_without_new_active_record(tmp_path: Path) -> None:
    project_dir = write_project_with_figures(tmp_path)
    save_project_style_override(
        project_dir,
        "figure-wetlands-waterbodies",
        [{"layer_id": "source:usfws_nwi_wetlands", "stroke_color": "#00AAFF"}],
    )

    result = save_project_style_override(
        project_dir,
        "figure-wetlands-waterbodies",
        [{"layer_id": "source:usfws_nwi_wetlands", "stroke_color": "#FFE500"}],
    )
    artifact = read_json(project_dir / FIGURE_STYLE_OVERRIDES_PATH)

    assert result["override_saved"] is False
    assert active_style_override(artifact, "figure-wetlands-waterbodies") is None
    assert artifact["overrides"][0]["status"] == "superseded"


def test_reset_project_style_override_preserves_audit_history(tmp_path: Path) -> None:
    project_dir = write_project_with_figures(tmp_path)
    save_project_style_override(
        project_dir,
        "figure-wetlands-waterbodies",
        [{"layer_id": "source:usfws_nwi_wetlands", "stroke_color": "#00AAFF"}],
    )

    result = reset_project_style_override(project_dir, "figure-wetlands-waterbodies")
    artifact = read_json(project_dir / FIGURE_STYLE_OVERRIDES_PATH)

    assert result["reset_count"] == 1
    assert artifact["override_count"] == 1
    assert artifact["overrides"][0]["status"] == "reset"
    assert artifact["overrides"][0]["reset_at"]
    assert active_style_override(artifact, "figure-wetlands-waterbodies") is None


def test_approve_figure_version_records_exact_version_and_supersedes_prior(tmp_path: Path) -> None:
    project_dir = write_project_with_figures(tmp_path)
    initialize_figure_style_model(project_dir)
    _append_test_version(project_dir, "figure-wetlands-waterbodies", 2)
    _append_test_version(project_dir, "figure-wetlands-waterbodies", 3)

    first = approve_figure_version(project_dir, "figure-wetlands-waterbodies", "figure-wetlands-waterbodies:v2", actor="reviewer_a")
    second = approve_figure_version(project_dir, "figure-wetlands-waterbodies", "figure-wetlands-waterbodies:v3", actor="reviewer_b")
    versions = read_json(project_dir / FIGURE_VERSIONS_PATH)
    v2 = next(item for item in versions["versions"] if item["version_id"] == "figure-wetlands-waterbodies:v2")
    v3 = next(item for item in versions["versions"] if item["version_id"] == "figure-wetlands-waterbodies:v3")

    assert first["version_id"] == "figure-wetlands-waterbodies:v2"
    assert second["previous_approved_version_id"] == "figure-wetlands-waterbodies:v2"
    assert v2["approval_state"] == "modified"
    assert v2["approved_version"] is False
    assert v2["approval_superseded_by_version_id"] == "figure-wetlands-waterbodies:v3"
    assert v3["approval_state"] == "approved"
    assert v3["approved_version"] is True
    assert v3["approved_by"] == "reviewer_b"
    assert v3["approved_at"]
    assert approved_figure_version(versions, "figure-wetlands-waterbodies")["version_id"] == "figure-wetlands-waterbodies:v3"


def test_reset_project_style_override_does_not_remove_approved_version(tmp_path: Path) -> None:
    project_dir = write_project_with_figures(tmp_path)
    save_project_style_override(
        project_dir,
        "figure-wetlands-waterbodies",
        [{"layer_id": "source:usfws_nwi_wetlands", "stroke_color": "#00AAFF"}],
    )
    _append_test_version(project_dir, "figure-wetlands-waterbodies", 2)
    approve_figure_version(project_dir, "figure-wetlands-waterbodies", "figure-wetlands-waterbodies:v2")

    reset_project_style_override(project_dir, "figure-wetlands-waterbodies")
    versions = read_json(project_dir / FIGURE_VERSIONS_PATH)

    assert approved_figure_version(versions, "figure-wetlands-waterbodies")["version_id"] == "figure-wetlands-waterbodies:v2"


@pytest.mark.parametrize(
    ("figure_id", "version_id", "message"),
    [
        ("figure-wetlands-waterbodies", "missing:v99", "is not available"),
        ("figure-stub-02", "figure-wetlands-waterbodies:v2", "is not available"),
        ("figure-wetlands-waterbodies", "figure-wetlands-waterbodies:v2", "output artifact is missing"),
    ],
)
def test_approve_figure_version_rejects_invalid_targets(
    tmp_path: Path,
    figure_id: str,
    version_id: str,
    message: str,
) -> None:
    project_dir = write_project_with_figures(tmp_path)
    initialize_figure_style_model(project_dir)
    _append_test_version(project_dir, "figure-wetlands-waterbodies", 2, write_output=False)

    with pytest.raises(FigureStyleModelError, match=message):
        approve_figure_version(project_dir, figure_id, version_id)


@pytest.mark.parametrize(
    ("layer", "message"),
    [
        ({"layer_id": "source:usfws_nwi_wetlands", "fill_color": "red"}, "fill_color must be"),
        ({"layer_id": "source:usfws_nwi_wetlands", "fill_opacity": "1.5"}, "fill_opacity must be between"),
        ({"layer_id": "source:usfws_nwi_wetlands", "stroke_width": "11"}, "stroke_width must be between"),
        ({"layer_id": "source:usfws_nwi_wetlands", "point_size": "0"}, "point_size must be between"),
        ({"layer_id": "source:usfws_nwi_wetlands", "z_index": "1000"}, "z_index must be between"),
        ({"layer_id": "source:usfws_nwi_wetlands", "label_field": "NOT_A_FIELD"}, "label_field"),
        ({"layer_id": "unknown", "stroke_color": "#00AAFF"}, "Unknown style override layer id"),
        ({"layer_id": "comparison_units:missing", "stroke_color": "#00AAFF"}, "Unknown style override layer id"),
        ({"layer_id": "source:usfws_nwi_wetlands", "buffer_distance": 50}, "Unsupported style override fields"),
    ],
)
def test_project_style_override_validation_rejects_bad_values(tmp_path: Path, layer: dict[str, object], message: str) -> None:
    project_dir = write_project_with_figures(tmp_path)

    with pytest.raises(FigureStyleModelError, match=message):
        save_project_style_override(project_dir, "figure-wetlands-waterbodies", [layer])


def test_style_save_and_reset_do_not_mutate_analysis_or_review_artifacts(tmp_path: Path) -> None:
    project_dir = write_project_with_figures(tmp_path)
    watched_paths = [
        project_dir / "deliverable" / "figures.json",
        project_dir / "source_status" / "source_status_set.json",
        project_dir / "context" / "project_area.json",
        project_dir / "intermediate" / "comparison_units.json",
        project_dir / "intermediate" / "comparison_units.geojson",
        project_dir / "constraints" / "comparison_unit_constraints.json",
        project_dir / "maps" / "figure_extent_plan.json",
    ]
    before = {path: path.read_bytes() for path in watched_paths}

    save_project_style_override(
        project_dir,
        "figure-wetlands-waterbodies",
        [{"layer_id": "source:usfws_nwi_wetlands", "stroke_color": "#00AAFF"}],
    )
    reset_project_style_override(project_dir, "figure-wetlands-waterbodies")

    assert {path: path.read_bytes() for path in watched_paths} == before
    assert not (project_dir / "review_queue" / "review_queue.json").exists()


def write_project_with_figures(tmp_path: Path) -> Path:
    project_dir = tmp_path / "project"
    (project_dir / "deliverable").mkdir(parents=True)
    (project_dir / "maps" / "figures").mkdir(parents=True)
    (project_dir / "layers" / "usfws_nwi_wetlands").mkdir(parents=True)
    (project_dir / "source_status").mkdir(parents=True)
    (project_dir / "context").mkdir(parents=True)
    (project_dir / "intermediate").mkdir(parents=True)
    (project_dir / "constraints").mkdir(parents=True)
    (project_dir / "maps").mkdir(parents=True, exist_ok=True)

    write_tiny_png(project_dir / "maps" / "figures" / "figure-wetlands-waterbodies.png")
    (project_dir / "layers" / "usfws_nwi_wetlands" / "usfws_nwi_wetlands.geojson").write_text(
        json.dumps(
            {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "properties": {"name": "wetland"},
                        "geometry": {
                            "type": "Polygon",
                            "coordinates": [[[-90.001, 31.999], [-89.999, 31.999], [-89.999, 32.001], [-90.001, 32.001], [-90.001, 31.999]]],
                        },
                    }
                ],
            }
        )
        + "\n",
        encoding="utf-8",
    )
    (project_dir / "intermediate" / "comparison_units.geojson").write_text(
        json.dumps(
            {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "properties": {"comparison_unit_id": "unit-1", "comparison_unit_name": "Alternative 1"},
                        "geometry": {"type": "LineString", "coordinates": [[-90.002, 32.0], [-89.998, 32.0]]},
                    },
                    {
                        "type": "Feature",
                        "properties": {"comparison_unit_id": "unit-2", "comparison_unit_name": "Alternative 2"},
                        "geometry": {"type": "LineString", "coordinates": [[-90.002, 32.001], [-89.998, 32.001]]},
                    }
                ],
            }
        )
        + "\n",
        encoding="utf-8",
    )
    for path in [
        project_dir / "source_status" / "source_status_set.json",
        project_dir / "context" / "project_area.json",
        project_dir / "intermediate" / "comparison_units.json",
        project_dir / "constraints" / "comparison_unit_constraints.json",
        project_dir / "maps" / "figure_extent_plan.json",
    ]:
        path.write_text("{}\n", encoding="utf-8")

    figures = [_figure_record(project_dir, "figure-wetlands-waterbodies", stub=False)]
    figures.extend(_figure_record(project_dir, f"figure-stub-{index:02d}", stub=True) for index in range(2, 16))
    artifact = {
        "project_id": "demo",
        "project_name": "Demo Project",
        "project_dir": str(project_dir),
        "created_at": "2026-05-22T00:00:00+00:00",
        "matrix_version": "test",
        "extent_policy": {},
        "figure_count": len(figures),
        "figures": figures,
        "attachment_supporting_figure_count": 0,
        "attachment_supporting_figures": [],
        "validation_issues": [],
        "upstream_artifacts": {},
        "output_path": str(project_dir / "deliverable" / "figures.json"),
    }
    (project_dir / "deliverable" / "figures.json").write_text(json.dumps(artifact, indent=2) + "\n", encoding="utf-8")
    return project_dir


def _figure_record(project_dir: Path, figure_id: str, *, stub: bool) -> dict[str, object]:
    image_path = project_dir / "maps" / "figures" / "figure-wetlands-waterbodies.png"
    layer_path = project_dir / "layers" / "usfws_nwi_wetlands" / "usfws_nwi_wetlands.geojson"
    return {
        "figure_id": figure_id,
        "type": "deliverable_figure",
        "figure_type": "deliverable_figure",
        "figure_number": 1,
        "title": "Wetlands and Waterbodies",
        "section_target_id": "wetlands-and-waterbodies",
        "image_path": "" if stub else str(image_path),
        "file_format": "png",
        "caption": "Wetlands and waterbodies in and near the project area.",
        "source_note": "Sources: National Wetlands Inventory.",
        "method_note": "Vector-only desktop screening map.",
        "map_elements": [] if stub else ["legend", "north_arrow", "scale_bar"],
        "figure_group": "deliverable_main",
        "related_resource_categories": ["wetlands_waterbodies"],
        "shown_layers": [] if stub else _shown_layers(layer_path),
        "source_refs": ["usfws_nwi_wetlands"],
        "layer_refs": [] if stub else [str(layer_path)],
        "related_constraint_ids": [],
        "comparison_unit_ids": ["unit-1", "unit-2"],
        "figure_policy": {"extent_policy": "direct"},
        "provenance": {"render_layout": {"extent_class": "small_direct"}},
        "uncertainty_flags": [],
        "is_stub": stub,
        "stub_text": "Empty stub for future implements whenever source data is accessible." if stub else "",
        "review_status": "needs_review" if stub else "draft",
        "validation_issues": [],
    }


def _shown_layers(layer_path: Path) -> list[dict[str, object]]:
    return [
        {
            "layer_type": "comparison_units",
            "label": "Comparison units",
            "feature_count": 2,
            "comparison_unit_ids": ["unit-1", "unit-2"],
            "geometry_type_counts": {"LineString": 2},
            "unit_styles": [
                {"comparison_unit_id": "unit-1", "label": "Alternative 1", "color": "#FF0000"},
                {"comparison_unit_id": "unit-2", "label": "Alternative 2", "color": "#0000FF"},
            ],
        },
        {
            "layer_type": "source_layer",
            "source_id": "usfws_nwi_wetlands",
            "label": "National Wetlands Inventory",
            "legend_label": "National Wetlands Inventory",
            "render_style": {
                "color": "#FFE500",
                "marker": "o",
                "line_width": 0.9,
                "polygon_alpha": 0.42,
                "point_alpha": 0.68,
                "style_source": "source_id_override",
            },
            "path": str(layer_path),
            "feature_count": 3,
            "geometry_type_counts": {"Polygon": 3},
        },
        {
            "layer_type": "basemap",
            "label": "USDA NAIP Project Basemap",
            "feature_count": 0,
            "geometry_type_counts": {},
        },
    ]


def write_tiny_png(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(
        base64.b64decode(
            "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lw9G"
            "xQAAAABJRU5ErkJggg=="
        )
    )


def _append_test_version(project_dir: Path, figure_id: str, version_number: int, *, write_output: bool = True) -> None:
    output_rel = f"maps/figures/versions/{figure_id}/v{version_number}.png"
    if write_output:
        write_tiny_png(project_dir / output_rel)
    artifact = read_json(project_dir / FIGURE_VERSIONS_PATH)
    artifact["versions"].append(
        {
            "version_id": f"{figure_id}:v{version_number}",
            "figure_id": figure_id,
            "version_number": version_number,
            "created_at": f"2026-05-22T00:00:0{version_number}+00:00",
            "created_by": "local_reviewer",
            "generated_by": "local_reviewer",
            "analysis_snapshot_id": "analysis-snapshot-test",
            "figure_recipe_id": f"{figure_id}:recipe:v1",
            "style_override_id": "",
            "render_job_id": f"{figure_id}:render-job:test-{version_number}",
            "output_artifact_path": output_rel,
            "file_format": "png",
            "approval_state": "regenerated",
            "is_stub": False,
            "source_image_status": "regenerated_review_only",
            "review_only": True,
            "export_active": False,
        }
    )
    artifact["version_count"] = len(artifact["versions"])
    (project_dir / FIGURE_VERSIONS_PATH).write_text(json.dumps(artifact, indent=2) + "\n", encoding="utf-8")


def read_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))
