"""Project-local figure recipe, style override, version, and render-job metadata."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .deliverable_figures import DELIVERABLE_FIGURES_PATH, DeliverableFigureError, load_deliverable_figures


FIGURE_RECIPES_PATH = Path("maps/figure_recipes/figure_recipes.json")
FIGURE_STYLE_OVERRIDES_PATH = Path("maps/figure_style_overrides/figure_style_overrides.json")
FIGURE_VERSIONS_PATH = Path("maps/figure_versions/figure_versions.json")
FIGURE_RENDER_JOBS_PATH = Path("maps/figure_render_jobs/figure_render_jobs.json")
FIGURE_VERSION_OUTPUT_DIR = Path("maps/figures/versions")
FIGURE_STYLE_MODEL_VERSION = "figure-style-model-v1"
SMALL_HASH_LIMIT_BYTES = 2_000_000

ANALYSIS_SNAPSHOT_ARTIFACTS = {
    "source_status": Path("source_status/source_status_set.json"),
    "project_area": Path("context/project_area.json"),
    "comparison_units_metadata": Path("intermediate/comparison_units.json"),
    "comparison_units_geojson": Path("intermediate/comparison_units.geojson"),
    "comparison_unit_constraints": Path("constraints/comparison_unit_constraints.json"),
    "figure_extent_plan": Path("maps/figure_extent_plan.json"),
    "deliverable_figures": DELIVERABLE_FIGURES_PATH,
}

ALLOWED_LAYER_OVERRIDE_FIELDS = {
    "visible",
    "z_index",
    "display_name",
    "legend_label",
    "fill_color",
    "fill_opacity",
    "stroke_color",
    "stroke_width",
    "point_marker",
    "point_size",
    "opacity",
    "label_visible",
    "label_field",
}

RENDER_JOB_STATUSES = {"queued", "running", "succeeded", "failed", "cancelled"}
FIGURE_VERSION_APPROVAL_STATES = {"autogenerated", "modified", "regenerated", "approved", "rejected"}


class FigureStyleModelError(RuntimeError):
    """Raised when figure style model metadata cannot be built or validated."""


def initialize_figure_style_model(project_dir: Path) -> dict[str, Any]:
    """Create project-local figure styling metadata from existing generated figures."""

    project_dir = project_dir.resolve()
    try:
        figures_artifact = load_deliverable_figures(project_dir)
    except DeliverableFigureError as exc:
        raise FigureStyleModelError(str(exc)) from exc

    now = _utc_now()
    snapshot = build_analysis_snapshot(project_dir, figures_artifact, created_at=now)
    recipes = [
        build_figure_recipe(
            project_dir,
            figure,
            snapshot["analysis_snapshot_id"],
            project_id=str(figures_artifact.get("project_id") or ""),
        )
        for figure in _all_figures(figures_artifact)
    ]
    versions = [build_autogenerated_version(figure, snapshot["analysis_snapshot_id"], created_at=now) for figure in _all_figures(figures_artifact)]

    recipes_artifact = {
        "schema_version": FIGURE_STYLE_MODEL_VERSION,
        "project_id": str(figures_artifact.get("project_id") or ""),
        "project_name": str(figures_artifact.get("project_name") or ""),
        "created_at": now,
        "analysis_snapshot_id": snapshot["analysis_snapshot_id"],
        "recipe_count": len(recipes),
        "recipes": recipes,
        "output_path": str(project_dir / FIGURE_RECIPES_PATH),
    }
    overrides_artifact = empty_style_overrides_artifact(figures_artifact, created_at=now)
    overrides_artifact["output_path"] = str(project_dir / FIGURE_STYLE_OVERRIDES_PATH)
    versions_artifact = {
        "schema_version": FIGURE_STYLE_MODEL_VERSION,
        "project_id": str(figures_artifact.get("project_id") or ""),
        "project_name": str(figures_artifact.get("project_name") or ""),
        "created_at": now,
        "analysis_snapshot_id": snapshot["analysis_snapshot_id"],
        "version_count": len(versions),
        "versions": versions,
        "output_path": str(project_dir / FIGURE_VERSIONS_PATH),
    }
    render_jobs_artifact = empty_render_jobs_artifact(figures_artifact, created_at=now)
    render_jobs_artifact["output_path"] = str(project_dir / FIGURE_RENDER_JOBS_PATH)

    validate_figure_recipes_artifact(recipes_artifact)
    validate_style_overrides_artifact(overrides_artifact)
    validate_figure_versions_artifact(versions_artifact)
    validate_render_jobs_artifact(render_jobs_artifact)

    _write_json(project_dir / FIGURE_RECIPES_PATH, recipes_artifact)
    _write_json(project_dir / FIGURE_STYLE_OVERRIDES_PATH, overrides_artifact)
    _write_json(project_dir / FIGURE_VERSIONS_PATH, versions_artifact)
    _write_json(project_dir / FIGURE_RENDER_JOBS_PATH, render_jobs_artifact)

    return {
        "project_id": str(figures_artifact.get("project_id") or ""),
        "project_name": str(figures_artifact.get("project_name") or ""),
        "created_at": now,
        "analysis_snapshot": snapshot,
        "recipes_path": str(project_dir / FIGURE_RECIPES_PATH),
        "style_overrides_path": str(project_dir / FIGURE_STYLE_OVERRIDES_PATH),
        "versions_path": str(project_dir / FIGURE_VERSIONS_PATH),
        "render_jobs_path": str(project_dir / FIGURE_RENDER_JOBS_PATH),
        "recipe_count": len(recipes),
        "version_count": len(versions),
        "override_count": 0,
        "render_job_count": 0,
        "mutated_artifact_paths": [
            str(FIGURE_RECIPES_PATH),
            str(FIGURE_STYLE_OVERRIDES_PATH),
            str(FIGURE_VERSIONS_PATH),
            str(FIGURE_RENDER_JOBS_PATH),
        ],
        "analysis_artifacts_mutated": False,
        "figure_images_mutated": False,
        "review_queue_mutated": False,
        "export_artifacts_mutated": False,
    }


def build_analysis_snapshot(project_dir: Path, figures_artifact: dict[str, Any], *, created_at: str | None = None) -> dict[str, Any]:
    project_dir = project_dir.resolve()
    artifact_refs = {
        key: _artifact_reference(project_dir, path)
        for key, path in ANALYSIS_SNAPSHOT_ARTIFACTS.items()
    }
    layer_paths = sorted(
        {
            _project_relative_path(project_dir, path)
            for figure in _all_figures(figures_artifact)
            for path in _figure_layer_paths(figure)
            if str(path or "").strip()
        }
    )
    payload_for_id = {
        "artifacts": artifact_refs,
        "layer_paths": layer_paths,
        "figure_ids": [str(figure.get("figure_id") or "") for figure in _all_figures(figures_artifact)],
    }
    snapshot_id = "analysis-snapshot-" + _sha256_json(payload_for_id)[:16]
    return {
        "analysis_snapshot_id": snapshot_id,
        "schema_version": FIGURE_STYLE_MODEL_VERSION,
        "project_id": str(figures_artifact.get("project_id") or ""),
        "created_at": created_at or _utc_now(),
        "snapshot_basis": "references_existing_review_assist_artifacts",
        "artifacts": artifact_refs,
        "layer_paths": layer_paths,
        "immutable_boundaries": {
            "source_layers_mutated": False,
            "source_status_mutated": False,
            "comparison_geometry_mutated": False,
            "constraints_mutated": False,
            "evidence_mutated": False,
            "tables_mutated": False,
            "report_policy_mutated": False,
        },
    }


def build_figure_recipe(project_dir: Path, figure: dict[str, Any], analysis_snapshot_id: str, *, project_id: str = "") -> dict[str, Any]:
    figure_id = _required_string(figure, "figure_id", "figure")
    layers = _recipe_layers(_dict_list(figure.get("shown_layers", [])))
    return {
        "recipe_id": f"{figure_id}:recipe:v1",
        "figure_id": figure_id,
        "project_id": project_id,
        "analysis_snapshot_id": analysis_snapshot_id,
        "matrix_target_id": figure_id,
        "section_target_id": str(figure.get("section_target_id") or ""),
        "figure_number": figure.get("figure_number"),
        "title": str(figure.get("title") or figure_id),
        "caption": str(figure.get("caption") or ""),
        "source_note": str(figure.get("source_note") or ""),
        "method_note": str(figure.get("method_note") or ""),
        "source_refs": _string_list(figure.get("source_refs", [])),
        "layer_refs": [_project_relative_path(project_dir, path) for path in _string_list(figure.get("layer_refs", []))],
        "default_layer_order": [layer["layer_id"] for layer in layers],
        "layers": layers,
        "extent_policy": _figure_extent_record(figure),
        "figure_policy": figure.get("figure_policy") if isinstance(figure.get("figure_policy"), dict) else {},
        "render_layout": _render_layout_from_provenance(figure),
        "generated_artifact": {
            "image_path": _project_relative_path(project_dir, str(figure.get("image_path") or "")),
            "file_format": str(figure.get("file_format") or "png"),
            "is_stub": bool(figure.get("is_stub", False)),
            "review_status": str(figure.get("review_status") or ""),
        },
        "presentation_only": True,
    }


def make_sparse_style_override(
    *,
    project_id: str,
    figure_id: str,
    analysis_snapshot_id: str,
    layers: list[dict[str, Any]],
    created_by: str = "reviewer",
    created_at: str | None = None,
) -> dict[str, Any]:
    """Return a sparse style override record, dropping unchanged/empty fields."""

    clean_layers: list[dict[str, Any]] = []
    for layer in layers:
        if not isinstance(layer, dict):
            raise FigureStyleModelError("Style override layer entries must be objects.")
        layer_id = str(layer.get("layer_id") or "").strip()
        if not layer_id:
            raise FigureStyleModelError("Style override layers require layer_id.")
        clean: dict[str, Any] = {"layer_id": layer_id}
        unknown = sorted(set(layer) - (ALLOWED_LAYER_OVERRIDE_FIELDS | {"layer_id"}))
        if unknown:
            raise FigureStyleModelError(f"Unsupported style override fields for layer '{layer_id}': {unknown}")
        for key in sorted(ALLOWED_LAYER_OVERRIDE_FIELDS):
            if key not in layer:
                continue
            value = layer[key]
            if value is None or value == "":
                continue
            clean[key] = value
        if len(clean) > 1:
            clean_layers.append(clean)
    now = created_at or _utc_now()
    override_id = f"{figure_id}:override:{_sha256_json({'layers': clean_layers, 'created_at': now})[:12]}"
    return {
        "override_id": override_id,
        "figure_id": figure_id,
        "project_id": project_id,
        "analysis_snapshot_id": analysis_snapshot_id,
        "created_by": created_by,
        "created_at": now,
        "updated_at": now,
        "overrides": clean_layers,
    }


def empty_style_overrides_artifact(figures_artifact: dict[str, Any], *, created_at: str | None = None) -> dict[str, Any]:
    return {
        "schema_version": FIGURE_STYLE_MODEL_VERSION,
        "project_id": str(figures_artifact.get("project_id") or ""),
        "project_name": str(figures_artifact.get("project_name") or ""),
        "created_at": created_at or _utc_now(),
        "override_count": 0,
        "overrides": [],
        "reset_to_default_policy": "remove_or_clear_sparse_override_only",
        "output_path": "",
    }


def reset_style_override(overrides_artifact: dict[str, Any], figure_id: str) -> dict[str, Any]:
    """Return a copy of the overrides artifact with a figure's overrides removed."""

    result = dict(overrides_artifact)
    result["overrides"] = [
        override
        for override in _dict_list(overrides_artifact.get("overrides", []))
        if str(override.get("figure_id") or "") != figure_id
    ]
    result["override_count"] = len(result["overrides"])
    result["updated_at"] = _utc_now()
    validate_style_overrides_artifact(result)
    return result


def build_autogenerated_version(figure: dict[str, Any], analysis_snapshot_id: str, *, created_at: str | None = None) -> dict[str, Any]:
    figure_id = _required_string(figure, "figure_id", "figure")
    image_path = str(figure.get("image_path") or "")
    return {
        "version_id": f"{figure_id}:v1",
        "figure_id": figure_id,
        "version_number": 1,
        "created_at": created_at or _utc_now(),
        "generated_by": "system",
        "analysis_snapshot_id": analysis_snapshot_id,
        "figure_recipe_id": f"{figure_id}:recipe:v1",
        "style_override_id": "",
        "render_job_id": "",
        "output_artifact_path": image_path,
        "file_format": str(figure.get("file_format") or "png"),
        "approval_state": "autogenerated",
        "is_stub": bool(figure.get("is_stub", False)),
        "source_image_status": "stub_without_image" if bool(figure.get("is_stub", False)) else "existing_generated_image",
    }


def make_render_job(
    *,
    project_id: str,
    figure_id: str,
    analysis_snapshot_id: str,
    figure_recipe_id: str,
    style_override_id: str = "",
    output_format: str = "png",
    status: str = "queued",
    created_at: str | None = None,
) -> dict[str, Any]:
    if status not in RENDER_JOB_STATUSES:
        raise FigureStyleModelError(f"Unsupported render job status: {status}")
    if output_format != "png":
        raise FigureStyleModelError("Sprint 6 render jobs support png output metadata only.")
    now = created_at or _utc_now()
    return {
        "render_job_id": f"{figure_id}:render-job:{_sha256_json({'recipe': figure_recipe_id, 'override': style_override_id, 'created_at': now})[:12]}",
        "project_id": project_id,
        "figure_id": figure_id,
        "analysis_snapshot_id": analysis_snapshot_id,
        "figure_recipe_id": figure_recipe_id,
        "style_override_id": style_override_id,
        "output_format": output_format,
        "status": status,
        "errors": [],
        "warnings": [],
        "started_at": "",
        "completed_at": "",
        "created_at": now,
    }


def empty_render_jobs_artifact(figures_artifact: dict[str, Any], *, created_at: str | None = None) -> dict[str, Any]:
    return {
        "schema_version": FIGURE_STYLE_MODEL_VERSION,
        "project_id": str(figures_artifact.get("project_id") or ""),
        "project_name": str(figures_artifact.get("project_name") or ""),
        "created_at": created_at or _utc_now(),
        "render_job_count": 0,
        "render_jobs": [],
        "output_path": "",
    }


def validate_figure_recipes_artifact(data: dict[str, Any]) -> None:
    recipes = _dict_list(data.get("recipes", []))
    if data.get("recipe_count") != len(recipes):
        raise FigureStyleModelError("Figure recipe count does not match recipes.")
    seen: set[str] = set()
    for recipe in recipes:
        recipe_id = _required_string(recipe, "recipe_id", "recipe")
        if recipe_id in seen:
            raise FigureStyleModelError(f"Duplicate figure recipe id: {recipe_id}")
        seen.add(recipe_id)
        _required_string(recipe, "figure_id", recipe_id)
        if not isinstance(recipe.get("layers"), list):
            raise FigureStyleModelError(f"Figure recipe '{recipe_id}' layers must be a list.")


def validate_style_overrides_artifact(data: dict[str, Any]) -> None:
    overrides = _dict_list(data.get("overrides", []))
    if data.get("override_count") != len(overrides):
        raise FigureStyleModelError("Figure style override count does not match overrides.")
    for override in overrides:
        _required_string(override, "override_id", "override")
        _required_string(override, "figure_id", "override")
        for layer in _dict_list(override.get("overrides", [])):
            unknown = sorted(set(layer) - (ALLOWED_LAYER_OVERRIDE_FIELDS | {"layer_id"}))
            if unknown:
                raise FigureStyleModelError(f"Unsupported style override fields: {unknown}")


def validate_figure_versions_artifact(data: dict[str, Any]) -> None:
    versions = _dict_list(data.get("versions", []))
    if data.get("version_count") != len(versions):
        raise FigureStyleModelError("Figure version count does not match versions.")
    seen: set[str] = set()
    for version in versions:
        version_id = _required_string(version, "version_id", "version")
        if version_id in seen:
            raise FigureStyleModelError(f"Duplicate figure version id: {version_id}")
        seen.add(version_id)
        _required_string(version, "figure_id", version_id)
        if int(version.get("version_number") or 0) < 1:
            raise FigureStyleModelError(f"Figure version '{version_id}' requires positive version_number.")
        if str(version.get("approval_state") or "") not in FIGURE_VERSION_APPROVAL_STATES:
            raise FigureStyleModelError(f"Figure version '{version_id}' has unsupported approval_state.")


def validate_render_jobs_artifact(data: dict[str, Any]) -> None:
    jobs = _dict_list(data.get("render_jobs", []))
    if data.get("render_job_count") != len(jobs):
        raise FigureStyleModelError("Figure render job count does not match render_jobs.")
    for job in jobs:
        _required_string(job, "render_job_id", "render_job")
        if str(job.get("status") or "") not in RENDER_JOB_STATUSES:
            raise FigureStyleModelError(f"Render job '{job.get('render_job_id')}' has unsupported status.")


def _recipe_layers(shown_layers: list[dict[str, Any]]) -> list[dict[str, Any]]:
    counters: dict[str, int] = {}
    layers: list[dict[str, Any]] = []
    for index, layer in enumerate(shown_layers):
        layer_type = str(layer.get("layer_type") or "layer")
        source_id = str(layer.get("source_id") or "").strip()
        layer_id = _stable_layer_id(layer_type, source_id, counters)
        render_style = layer.get("render_style") if isinstance(layer.get("render_style"), dict) else {}
        default_style = _default_style_from_render_style(render_style)
        layers.append(
            {
                "layer_id": layer_id,
                "layer_type": layer_type,
                "source_id": source_id,
                "default_z_index": index,
                "default_visible": True,
                "default_display_name": str(layer.get("label") or layer.get("legend_label") or layer_id),
                "default_legend_label": str(layer.get("legend_label") or layer.get("label") or layer_id),
                "default_style": default_style,
                "feature_count": int(layer.get("feature_count") or 0),
                "geometry_type_counts": layer.get("geometry_type_counts") if isinstance(layer.get("geometry_type_counts"), dict) else {},
                "path": str(layer.get("path") or ""),
                "comparison_unit_ids": _string_list(layer.get("comparison_unit_ids", [])),
                "unit_styles": _dict_list(layer.get("unit_styles", [])),
                "editable_presentation_fields": sorted(ALLOWED_LAYER_OVERRIDE_FIELDS),
            }
        )
    return layers


def _stable_layer_id(layer_type: str, source_id: str, counters: dict[str, int]) -> str:
    if layer_type == "comparison_units":
        base = "comparison_units"
    elif layer_type == "source_layer" and source_id:
        base = f"source:{source_id}"
    elif layer_type == "basemap":
        base = "basemap"
    elif layer_type == "basemap_provenance":
        base = "basemap_provenance"
    else:
        base = layer_type or "layer"
    count = counters.get(base, 0)
    counters[base] = count + 1
    if base in {"basemap", "basemap_provenance"}:
        return f"{base}:{count + 1}"
    if count:
        return f"{base}:{count + 1}"
    return base


def _default_style_from_render_style(render_style: dict[str, Any]) -> dict[str, Any]:
    return {
        "fill_color": render_style.get("color"),
        "fill_opacity": render_style.get("polygon_alpha"),
        "stroke_color": render_style.get("color"),
        "stroke_width": render_style.get("line_width"),
        "point_marker": render_style.get("marker"),
        "point_size": render_style.get("marker_size"),
        "opacity": render_style.get("point_alpha") or render_style.get("line_alpha") or render_style.get("polygon_alpha"),
        "style_source": render_style.get("style_source"),
    }


def _figure_extent_record(figure: dict[str, Any]) -> dict[str, Any]:
    keys = (
        "extent_policy",
        "visual_extent_class",
        "rendering_extent_class",
        "source_query_extent",
        "figure_extent",
        "render_extent",
        "presentation_extent",
        "presentation_extent_type",
    )
    return {key: figure.get(key) for key in keys if key in figure}


def _render_layout_from_provenance(figure: dict[str, Any]) -> dict[str, Any]:
    provenance = figure.get("provenance") if isinstance(figure.get("provenance"), dict) else {}
    layout = provenance.get("render_layout") if isinstance(provenance.get("render_layout"), dict) else {}
    return dict(layout)


def _figure_layer_paths(figure: dict[str, Any]) -> list[str]:
    paths = list(_string_list(figure.get("layer_refs", [])))
    for layer in _dict_list(figure.get("shown_layers", [])):
        path = str(layer.get("path") or "").strip()
        if path:
            paths.append(path)
    return paths


def _all_figures(figures_artifact: dict[str, Any]) -> list[dict[str, Any]]:
    return [*_dict_list(figures_artifact.get("figures", [])), *_dict_list(figures_artifact.get("attachment_supporting_figures", []))]


def _artifact_reference(project_dir: Path, relative_path: Path) -> dict[str, Any]:
    path = project_dir / relative_path
    record: dict[str, Any] = {
        "path": str(relative_path).replace("\\", "/"),
        "exists": path.exists(),
    }
    if not path.exists():
        return record
    stat = path.stat()
    record["size_bytes"] = int(stat.st_size)
    record["modified_at"] = datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat()
    if path.is_file() and path.suffix.lower() in {".json", ".geojson"} and stat.st_size <= SMALL_HASH_LIMIT_BYTES:
        record["sha256"] = hashlib.sha256(path.read_bytes()).hexdigest()
    return record


def _project_relative_path(project_dir: Path, value: str | Path) -> str:
    if not str(value or "").strip():
        return ""
    path = Path(value)
    if not path.is_absolute():
        return str(path).replace("\\", "/")
    try:
        return path.resolve().relative_to(project_dir.resolve()).as_posix()
    except ValueError:
        return str(path)


def _required_string(record: dict[str, Any], key: str, label: str) -> str:
    value = record.get(key)
    if not isinstance(value, str) or not value.strip():
        raise FigureStyleModelError(f"{label} requires non-empty {key}.")
    return value


def _dict_list(value: Any) -> list[dict[str, Any]]:
    return [item for item in value if isinstance(item, dict)] if isinstance(value, list) else []


def _string_list(value: Any) -> list[str]:
    return [str(item) for item in value if str(item).strip()] if isinstance(value, list) else []


def _sha256_json(value: Any) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()
